<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-07-05T13:29:21Z" name="Default suite" finished-at="2019-07-05T13:29:44Z" duration-ms="23273">
    <groups>
    </groups>
    <test started-at="2019-07-05T13:29:21Z" name="Default test" finished-at="2019-07-05T13:29:44Z" duration-ms="23273">
      <class name="com.training.sanity.tests.RETC_012_ResetPassword">
        <test-method is-config="true" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.RETC_012_ResetPassword@38e79ae3]" started-at="2019-07-05T13:29:21Z" name="setUpBeforeClass" finished-at="2019-07-05T13:29:21Z" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.training.sanity.tests.RETC_012_ResetPassword@38e79ae3]" started-at="2019-07-05T13:29:21Z" name="setUp" finished-at="2019-07-05T13:29:33Z" duration-ms="12254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="resetPassword()[pri:0, instance:com.training.sanity.tests.RETC_012_ResetPassword@38e79ae3]" started-at="2019-07-05T13:29:33Z" name="resetPassword" finished-at="2019-07-05T13:29:42Z" duration-ms="9019" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [A confirmation link has been sent to your email address] but found [The email could not be sent.
Possible reason: your host may have disabled the mail() function.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [A confirmation link has been sent to your email address] but found [The email could not be sent.
Possible reason: your host may have disabled the mail() function.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.training.sanity.tests.RETC_012_ResetPassword.resetPassword(RETC_012_ResetPassword.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.training.sanity.tests.RETC_012_ResetPassword@38e79ae3]" started-at="2019-07-05T13:29:42Z" name="tearDown" finished-at="2019-07-05T13:29:44Z" duration-ms="1929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.RETC_012_ResetPassword -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
